# Generated by Django 5.1.6 on 2025-02-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bid_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='current_bid',
            new_name='highest_bid',
        ),
    ]
