# Generated by Django 5.1.6 on 2025-02-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_current_bid_auction_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='highest_bid',
            field=models.IntegerField(default=0),
        ),
    ]
