# Generated by Django 5.1.6 on 2025-03-01 10:13

import auctions.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_starting_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='starting_bid',
        ),
        migrations.AlterField(
            model_name='auction',
            name='highest_bid',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.URLField(blank=True, validators=[auctions.models.validateURL]),
        ),
    ]
