# Generated by Django 5.1.6 on 2025-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='starting_price',
            field=models.IntegerField(default=1),
        ),
    ]
